let types = {
    USER_LOGGED_IN:'USER_LOGGED_IN',
    USER_LOGGING_IN:'USER_LOGGING_IN',
    USER_LOGGED_OUT:'USER_LOGGED_OUT',
    USER_LOG_IN_FAIL: 'USER_LOG_IN_FAIL',
    USER_LOGGING_OUT: 'USER_LOGGING_OUT',
    USER_REGISTERED:'USER_REGISTERED',
    USER_REGISTER_FAIL: 'USER_REGISTER_FAIL',
    USER_REGISTERING:'USER_REGISTERING',
    USER_AUTHENTICATE: 'USER_AUTHENTICATE',
    USER_AUTHENTICATED: 'USER_AUTHENTICATED',
    USER_AUTHENTICATE_FAIL: 'USER_AUTHENTICATE_FAIL'
}

export default types